language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: FfX6JSf49W57odbj5P1NtJi7Nr14wJb99Xf4t6KrwyZXTAZNryRHrOGvDDDCQ204hyvw65R95tViRTngfxKBfgtWXu9mng1Qpff2v/O3fgJsB8K6vO9OmOFAMvhSaAnP+4tltKQTFwEg59He1M9bMzC0ZfWkC1yx64tXvRb0JkNsRwT/PfxA6EhF4T5Z+gnECaUZ7nkUVoTAXO+enHiM7mALChXvtEEnzKEJwsvTM4Oa9/AIjsRTIlOIIlM+nglzH+FgrE8Ey5pPU5c6WfJMSMeLLKLD33QJwLhZ0RSrMN7n1oFbtfLYDNPGxHNnouqhOD4+fTF1vem1SoX+7iV8ijI8HpkHB8z4nWJovbuS9pxIfreXK9vcXgiQ62ZB8ELhw8FUa7ck2lmhdoOeSuFpTaP9zwFoM6lnovs0py9TLx98qVsv5Fb3jXylZSSNbRjR+qSa0ES8WxurzkmO20IKVeuGzNZJWR6SyFdUT3iZ6fX3wDnjEiL79Dwc9AAmpjmLVcHd0ipcXCD6U+FwpQXoGfJCy8/n2dWMLUVoUWWQK5AIqQHHA8GeTSGorCC7/BBRi8U8tQIGU+jG5w4/JNTm3Hw5V1o5nxbyYhgRDk0WAitTH/EvFB+mUflBvKrglwtvHv6e30FwT0gwgH9QKJ/hiaZlewG1+3cPyMj9WmoGDWM=
  app: webcom-status
  on:
    branch: main
    repo: russellkoons/webcom-status
