language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: PkBBuxrAyy5gU91ZYQRGVaGICtZqizsYHISYOrQMooIOjTf8WsdFs7P+ZacAY149lQFb8QnVpLZ99wOu8dJBYoERIqEL4+g+p5yUEkSenI7CLB/5ySEUhXU/Ki1gDCxu/QgujzFSFo6/tLzKe9/KKHPHflilZzZqCSW42FxzISyQfffGLbEq4lKEEvP9jnCV/K7SAWoLMOJrs5JKmKezvL6U95HiNf3Nms943exO7UL4AXd09PoEuIyZYeTsQZfFdSLUnGlEkkisyZZKigTtZOV+9iUXA/ytWBmYhLBwruFa/uf7q8dM9259zyqx39C9C+18ZojA6bKR7r7VVPCe01IV6gXkWWXCnL4xIvxNzleaB8FQHBh4X81OFItUy5Be38qJ63CAinPcWfl2jVEntyKl43aGkds2kaKJGIXKoeYb9btGBbHKVavLpxWG0qITlKrJP7nTH07ylKLEqZJhm2+6x+9VzVpKLe2+ZG0Jtc9DHbg1sTLqLsa6wUtN5HkEuSfIBWudXb41i9i6JGUo1YbAkuiG12rQz3ySIhSwUzf37sl+h/pVv4e0jxm2MAtauqvBzQt4FNPaEpN/QjOdX524FfdUQjiQi/auE6GGGMwyr6T44/pfdW1vsp1euBr9FGlBLTkIP1z3wAJ2ZJ7TAqU8g1Z1LL+5AC6GDGBydPc=
  app: webcom-status
  on:
    branch: main
    repo: russellkoons/webcom-status
