language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: uPeo+SFe1WB2KDtQi5+F/h994xuOeXaTkxLi4xGKUbOyMUXNejXj3q5GPBquMc6udP31QPkfgPTlY0DVjWgmeC/wlf2R/XMiiNuvZQR3NVt5TBu77Q5GPPNWYem7k0+rrapEPbht9uJTdQd6fqnMSPj877zlbsFU7ATrnUX/Xwof4Wnxzo8sjLD0GS5ABZq8NtbVgdM1cOs5viV8tBF62Ay1V/A4r2qv/oddoLFwAw6m5Gvx2VduksHb7BuwS3vPi+rzdsoLYF6Pt650Jq8UUAn4UbGl28yZC+qeI0UzzelnGRIYDZbqkz8NA4J4n5sPesf06fsfRSpppswpiTmJjxxLD+YoU/c4f6TohW2BEiH0NS9B1gm8ih4hoyoBau+YwHACd9SFU31R4x1dMMRkSqjflu3JT5YAJzwR/DXEjDp0zUQtAKMisHigYAbtZyLH5wWypRyOrNX40pKvY7kfgf7gSoZbQV1IQI/sZ3sMNXH4xazZFwTSxRGxHXC1uEN9nJZFohdpUjVIrNHQPDCKU3CmvBlHcnHGpP3r8rUdoa6uqbSOab4UsrxfCMTml2mPmo0RpegIGwIDB2znXew+QwAsODr9nXwNvYZTGjxkyc3pfRqj3pz0fIGK1v27+SlGwAXLJt7LUDTy9dWurfGISghgdypEJGI3VoXDrDRJgBM=
  app: webcom-status
  on:
    branch: main
    repo: russellkoons/webcom-status
