language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: vFPR6ZjauHfRmuHWJxxb9OUF7To9FtPNjSbo6ziKpPvQFBPM84j1lQjEMn/DM6qvE/iPMjEqm0iP1ZkA2yjRUq04pICUiL/KA/J0CRv00oN+xaDFzm69MZ+LeLFyJhRTWPX9zx2jqsd9tRdA7NAGJ8xn7hNzEJCK/8Nw7oOiTkhaJPTxwKQCVh5jtwgBUOBvxZoxQzDc39JnoAMCBG4fAc9p5Qpjk9m+wIPDfN3WZdKL+zA73rYrXa1fk+cNB6QQLFH1rADg6TvWP+xh20N8rWsfUNzgYeuGrUv6PeULzPyryTfANa0W3ZHlP3cePRK7K9BX+bxicanSeNSK70/mMJJcBdAfsL7Y8On0sZIyBjsY67F7ZYvWY15Ll2P4GSOBy+lJWDIpV3uOSxEbQG7Rw4pX8PkYTu2b7hUDcL2WEWwdAEBXvSoxilgp2CxFIT5LvSVk8tCJhC0NxyP6SWD3VpO7m9tlBKxeBAtokjsrsdVGWYUzGsHUfAbHWSmXA5LStwCoF7VL2nV/9lm/L4wiGqSOm9LV1Gto2pPQQCKKGusjZYJBQC7IEDlLOfQP3cMQVAkVG3U2LsOfJ33A1isiDRilPdEfoQPEpen7M39FI7ELDj0z4AjW/2o/m/w8Qc/sEx2LV5Wwm9+O1MTHVSwzbJFbC2HrWZRbgurYawHTcII=
  app: webcom-status
  on:
    branch: main
    repo: russellkoons/webcom-status
